### ISSUE TITLE
DocumentDB: Connection timeout from parse-dashboard

### ISSUE THREAD

**Issue by ekrylovich** [felixrieseberg/parse-server-azure#12]
Hello,

I just installed parse server on azure services and faced problem with displaying data in parse-dashboard. I just create parse server on azure according to this article, everything before migrating your app part:
https://azure.microsoft.com/en-us/blog/announcing-the-publication-of-parse-server-with-azure-managed-services/
Just after my data from parse.com was migrated, i go to azure-parse-dashboard and trying to verify my collection. But when I try to display table with 515k records - it display nothing. When I go logs section I found this error there:

2016-10-23T18:57:56.191Z - Uncaught internal server error. { [MongoError: connection 51 to ziveparseserverdb-parse.documents.azure.com:10250 timed out]
  name: 'MongoError',
  message: 'connection 51 to ziveparseserverdb-parse.documents.azure.com:10250 timed out' } MongoError: connection 51 to ziveparseserverdb-parse.documents.azure.com:10250 timed out
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\mongodb-core\lib\error.js:29:11)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\connection.js:173:20)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
2016-10-23T18:57:56.191Z - Error generating response. { [MongoError: connection 51 to ziveparseserverdb-parse.documents.azure.com:10250 timed out]
  name: 'MongoError',
  message: 'connection 51 to ziveparseserverdb-parse.documents.azure.com:10250 timed out' }

When i tried to display the same collection with filter - seems everything is ok. 

How can I fix displaying all my data correctly???

Thanks in advance, Egor

**Comment by adrianhall** [comment]
@aliuy Can you check into this?
